config/routes.rb
Annotext::Application.routes.draw do

  root  'texts#index'
  match '/help',        to: 'static_pages#help',        via: 'get'
  match '/editor_help', to: 'static_pages#editor_help', via: 'get'
  match '/about',       to: 'static_pages#about',       via: 'get'
  match '/contact',     to: 'static_pages#contact',     via: 'get'
  match '/history',     to: 'static_pages#history',     via: 'get'

  match '/signin',      to: 'sessions#new',             via: 'get'
  match '/signout',     to: 'sessions#destroy',         via: 'delete'

  match '/scripts',     to: 'scripts#index',            via: 'get'
  match '/complete',    to: 'scripts#complete',         via: 'get'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :texts do
    collection do
      get :order #'order'     # !!! Shouldn't be a get...
    end
    member do
      patch :release, :save, :delete, :save_about
      get   :about
    end
  end

  resources :media do
    member do
      get :close
    end
  end

  resources :matches,     only: [:create, :show, :edit, :update, :destroy]
  resources :phrases,     only: [:create, :show, :edit, :update, :destroy]
  resources :definitions, except: [:index] do
    member do
      post :copy_to_gloss, :copy_to_dict
      get  :close
    end
  end

  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  has_many :texts

  before_save { self.email = email.downcase }
  before_save { self.name = name.downcase }
  before_create :create_remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :name,     presence:   true,
                       length:     { maximum: 30 },
                       uniqueness: { case_sensitive: false }

  validates :email,    presence:   true, 
                       format:     { with: VALID_EMAIL_REGEX },
                       uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length:     { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user,  only: [:edit, :update]
  before_action :admin_user,    only: [:destroy, :new, :create]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @texts = @user.texts
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "A new user has been successfully created!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 20)
  end

  def destroy
    @user = User.find(params[:id])
    if current_user?(@user)
      redirect_to(root_url)
    else
      @user.destroy
      flash[:success] = "User deleted."
      redirect_to users_path
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<li>
  <%= link_to user.name + " (" + user.email + ")", user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, 
                                  data: { confirm: "Are you sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Save changes", class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'New User') %>
<h1>Create New User</h1>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Create an account", class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<p class="bg-info">
  The texts displayed here are those texts which you have ownership over.
  However, the order in which the texts are displayed can only be modified on
  the general <%= link_to "texts", texts_path %> page.
</p>

<div class="span8">
  <% if @user.texts.any? %>
    <h3>
      Texts (<%= @user.texts.count %>) belonging to 
      <%= @user.name %> (<%= @user.email %>)
    </h3>
    <ul class="texts">
      <%= render @texts %>
    </ul>
  <% else %>
    <h3> You currently own no texts. </h3>
  <% end %>
</div>