config/routes.rb
Annotext::Application.routes.draw do

  root  'texts#index'
  match '/help',        to: 'static_pages#help',        via: 'get'
  match '/editor_help', to: 'static_pages#editor_help', via: 'get'
  match '/about',       to: 'static_pages#about',       via: 'get'
  match '/contact',     to: 'static_pages#contact',     via: 'get'
  match '/history',     to: 'static_pages#history',     via: 'get'

  match '/signin',      to: 'sessions#new',             via: 'get'
  match '/signout',     to: 'sessions#destroy',         via: 'delete'

  match '/scripts',     to: 'scripts#index',            via: 'get'
  match '/complete',    to: 'scripts#complete',         via: 'get'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :texts do
    collection do
      get :order #'order'     # !!! Shouldn't be a get...
    end
    member do
      patch :release, :save, :delete, :save_about
      get   :about
    end
  end

  resources :media do
    member do
      get :close
    end
  end

  resources :matches,     only: [:create, :show, :edit, :update, :destroy]
  resources :phrases,     only: [:create, :show, :edit, :update, :destroy]
  resources :definitions, except: [:index] do
    member do
      post :copy_to_gloss, :copy_to_dict
      get  :close
    end
  end

  

end

app/views/shared/_add_to_button.html.erb
<% if !@creating %>
  <% if entry.text_id == nil %>
    <%= render 'shared/add_to_gloss', entry: entry %>
  <% else %>
    <%= render 'shared/add_to_dict', entry: entry %>
  <% end %>
<% end %>

app/views/shared/_add_to_dict.html.erb
<%= form_tag(copy_to_dict_definition_path(entry.id), method: 'post', remote: true, class: "add-form") do %>
  <%= submit_tag "Add to dictionary", class: "btn btn-xs btn-primary" %>
<% end %>

app/views/shared/_add_to_gloss.html.erb
<%= form_tag(copy_to_gloss_definition_path(entry.id), method: 'post', remote: true, class: "add-form") do %>
  <%= hidden_field_tag "text_id", @text_id %>
  <%= submit_tag "Add to glossary", class: "btn btn-xs btn-primary" %>
<% end %>

app/views/shared/_close_def_button.html.erb
<% if !@creating %>
  <%= link_to close_definition_path(@definition, text: @text_id),
          remote: true, class: "close",
          title: "Close without saving. All unsaved changes will be lost." do %>
    <span aria-hidden="true">&times;</span>
  <% end %>
<% end %>

app/views/shared/_definition_form.html.erb
<% if @definition != nil %>
  <%= form_for(@definition, remote: true) do |f| %>
    <%= render 'shared/flash_ajax', flash: flash %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= render 'shared/close_def_button' %>

    <%= f.label :term %>
    <%= f.text_field :term, class: "form-control" %>

    <%= f.label :lex_class %>
    <%= f.text_field :lex_class, class: "form-control" %>

    <%= f.label :definition %>
    <%= f.text_area :definition, class: "form-control" %>

    <%= f.label :hits %>
    <% if @match_string %>
      <%= f.text_area :hits, class: "form-control", value: @match_string,
                                                id: "hits_#{@definition.id}" %>
    <% else %>
      <%= f.text_area :hits, class: "form-control",
                                                id: "hits_#{@definition.id}" %>
    <% end %>

    <%= f.hidden_field :text_id %>
    <%= f.hidden_field :editing_text_id, value: @text_id %>

    <%= f.submit "#{@button_caption} definition", title: "Save changes.",
                 onclick: "return prepareHits('#{@definition.id}');",
                 class: "btn btn-primary btn-xs", 
                 :data => { :disable_with => "Processing" } %>

    <%= render 'shared/revert_cancel_def_button' %>
  <% end %>

  <%= render 'shared/add_to_button', entry: @definition %>
<% end %>

app/views/shared/_dictionary_definitions.html.erb
<span class='count'>Dictionary Matches: <span id='dict-count'></span></span>

<ol class="definitions" id="dict-definitions">
</ol>

app/views/shared/_entry.html.erb
<li id="def-<%= entry.id %>">
  <span class="term"><%= entry.term %></span>
  <span class="lex_class"><%= entry.lex_class %></span>
  <span class="definition"><%= entry.definition %></span>
  <br>
  <b>Matches: </b><span class="match-list"><%= entry.hits %></span>
  <br>
  <%= link_to "Edit", edit_definition_path(entry, text: @text_id),
                      class: "btn btn-primary btn-xs", remote: true %>
  <%= link_to "Delete", entry, method: :delete,
                               data: { confirm: "Are you sure?" },
                               title: entry.term,
                               class: "btn btn-primary btn-xs",
                               remote: true %>
  <%= render 'shared/add_to_button', entry: entry %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_ajax.html.erb
<% if flash[:success] %>
  <div class="alert alert-success"><%= flash[:success] %></div>
<% end %>

<% if flash[:info] %>
  <div class="alert alert-info"><%= flash[:info] %></div>
<% end %>

<% if flash[:warning] %>
  <div class="alert alert-warning"><%= flash[:warning] %></div>
<% end %>

<% if flash[:danger] %>
  <div class="alert alert-danger"><%= flash[:danger] %></div>
<% end %>

app/views/shared/_glossary_definitions.html.erb
<span class='count'>Glossary Matches: <span id='gloss-count'></span></span>

<ol class="definitions" id="gloss-definitions">
</ol>

<span id="new-definition"></span>

app/views/shared/_lookup_box.html.erb
<%= form_tag(match_path, :method => "get", remote: true) do %>
  <%= text_field_tag :word, params[:word], placeholder: "Search Matches" %>
  <%= hidden_field_tag :text, params[:id] %>
  <%= submit_tag "Search", :name => nil %>
<% end %>

app/views/shared/_new_glossary_def.html.erb
<span id="new-gloss-def">
  <%= link_to "Create New Definition", 
                      new_definition_path(text: @text_id, str: @match_string), 
                      class: "btn btn-warning btn-xs", remote: true %>
</span>

app/views/shared/_phrase_definition.html.erb
<div class="phrase-display">
  <b>Clicked Phrase ID: </b><span class="id"><%= @phrase.id %></span><br>
  <br>
  <div class="term"><%= @phrase.term %></div>
  <div class="definition"><%= @phrase.definition %></div>
  <br>
  <em>Please select the button in the editor to modify this phrase.</em>
</div>

app/views/shared/_revert_cancel_def_button.html.erb
<% if @creating %>
  <button type="button" class="btn btn-primary btn-xs" id="cancel-new-def">
    Cancel
  </button>
<% else %>
  <%= link_to "Revert", edit_definition_path(@definition),
              class: "btn btn-primary btn-xs", remote: true, 
              title: "Revert to most recently saved definition.",
              :data => { :disable_with => "Processing" } %>
<% end %>