config/routes.rb
Annotext::Application.routes.draw do

  root  'texts#index'
  match '/help',        to: 'static_pages#help',        via: 'get'
  match '/editor_help', to: 'static_pages#editor_help', via: 'get'
  match '/about',       to: 'static_pages#about',       via: 'get'
  match '/contact',     to: 'static_pages#contact',     via: 'get'
  match '/history',     to: 'static_pages#history',     via: 'get'

  match '/signin',      to: 'sessions#new',             via: 'get'
  match '/signout',     to: 'sessions#destroy',         via: 'delete'

  match '/scripts',     to: 'scripts#index',            via: 'get'
  match '/complete',    to: 'scripts#complete',         via: 'get'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :texts do
    collection do
      get :order #'order'     # !!! Shouldn't be a get...
    end
    member do
      patch :release, :save, :delete, :save_about
      get   :about
    end
  end

  resources :media do
    member do
      get :close
    end
  end

  resources :matches,     only: [:create, :show, :edit, :update, :destroy]
  resources :phrases,     only: [:create, :show, :edit, :update, :destroy]
  resources :definitions, except: [:index] do
    member do
      post :copy_to_gloss, :copy_to_dict
      get  :close
    end
  end

  

end

app/models/text.rb
# == Schema Information
#
# Table name: texts
#
#  id           :integer          not null, primary key
#  title        :string(255)
#  author       :string(255)
#  lang_from_id :integer
#  lang_to_id   :integer
#  created_at   :datetime
#  updated_at   :datetime
#  user_id      :integer
#  position     :integer
#  released     :boolean
#

class Text < ActiveRecord::Base
  belongs_to :user
  has_many :definitions, dependent: :destroy
  has_many :phrases, dependent: :destroy
  has_many :media, dependent: :destroy

  default_scope -> { order('position ASC') }

  validates :title, presence: true,   length: { maximum: 80 }
  validates :author,                  length: { maximum: 40 }
  validates :user_id, presence: true
  validates :position, presence: true
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :signed_in_user, except: [:index, :show, :about]
  before_action :has_permission, only: [:edit]

  def new
    @text = Text.new
  end

  def create
    @position = ( (@position=Text.all.pluck(:position).max) ? @position+1 : 1)
    @text = current_user.texts.build(text_params)
    @text.position = @position
    @text.released = false
    if @text.save
      Dir.mkdir(Rails.root.join('app', 'assets', 'texts', "#{@text.id}"))
      Dir.mkdir(Rails.root.join('app', 'assets', 'texts', "#{@text.id}",
                                                                      'media'))
      File.new(       text_loc(@text.id), "w+")
      File.new( about_text_loc(@text.id), "w+")
      redirect_to edit_text_path(@text)
    else
      render 'new'
    end
  end

  def edit
    @text = Text.find(params[:id])
    @content = File.read( text_loc(params[:id]) ).html_safe
    @about_content = File.read( about_text_loc(params[:id]) ).html_safe
    @media = Medium.where("text_id = ?", params[:id])
  end

  def update
    respond_to do |format|
      format.js {
        @text = Text.find(params[:id])
        if @text.update_attributes(text_params)
          # Errors displayed automatically
          flash.now[:success] = "Title and author updated!"
        end
      }
    end
  end

  def save
    respond_to do |format|
      format.json {
        @text = params[:id]
        @content = params[:content]
        File.open( text_loc(params[:id]), "w+") do |f|
          f.write(@content)
        end
        render :json => { :success => true } # Needed this to get ajax response.
      }
    end
  end

  def release
    respond_to do |format|
      format.js {
        @text = Text.find(params[:id])
        @text.toggle!(:released)
      }
    end
  end

  def index
    if signed_in?
      @texts = Text.all
    else
      @texts = Text.where("released = ?", true).load
    end
  end

  def order
    if params[:text]
      params[:text].each_with_index { 
        |text, index| Text.update(text.to_i, :position => (index))
      }
      flash[:info] = "Text order has been updated."
      redirect_to(texts_path)
    else
    end
  end

  def show
    @text = Text.find(params[:id])
    @content = File.read( text_loc(params[:id]) ).html_safe
    get_glossary(params[:id]) # Retrieves text matches, definitions, and phrases
  end

  def about
    @text = Text.find(params[:id])
    @content = File.read( about_text_loc(params[:id]) ).html_safe
  end

  def save_about
    respond_to do |format|
      format.json {
        @text = params[:id]
        @content = params[:content]
        File.open( about_text_loc(params[:id]), "w+") do |f|
          f.write(@content)
        end
        render :json => { :success => true } # Needed this to get ajax response.
      }
    end
  end


  private

    def text_params
      params.require(:text).permit(:title, :author)
    end

    # Before filters

    def has_permission
      @text = Text.find(params[:id])
      @user = User.find(@text.user_id)
      unless current_user?(@user)
        flash[:warning] = "You do not have permission to modify #{@text.title}."
        redirect_to texts_path
      end
    end
end

app/helpers/texts_helper.rb
module TextsHelper
  def get_glossary(text)
    get_matches(text)
    get_definitions(text)
    get_phrases(text)
  end

  def get_matches(text)
    @matches = {}
    raw = Match.where("text_id = ?", text).pluck(:word, :definition_id)
    raw.each do |m|
      if @matches[m[0]]
        @matches[m[0]].push(m[1])
      else
        @matches[m[0]] = [m[1]]
      end
    end
  end

  def get_definitions(text)
    @definitions = {}
    raw = Definition.where("text_id = ?", text).
                                pluck(:id, :term, :lex_class, :definition)
    raw.each do |d|
      @definitions[d[0]] = [d[1],d[2],d[3]]
    end
  end

  def get_phrases(text)
    @phrases = {}
    raw = Phrase.where("text_id = ?", text).pluck(:id, :term, :definition)
    raw.each do |p|
      @phrases[p[0]] = [p[1],p[2]]
    end
  end

  def text_loc(id)
    Rails.root.join('app', 'assets', 'texts', "#{id}", "#{id}.html")
  end

  def about_text_loc(id)
    Rails.root.join('app', 'assets', 'texts', "#{id}", "about.html")
  end

  def showing_text?
    (params[:controller]=="texts" && params[:action]=="show")
  end

  def editing_text?
    (params[:controller]=="texts" && params[:action]=="edit")
  end
end

app/views/texts/_release.html.erb
<%= form_tag(release_text_path(text.id), method: 'patch', remote: true,
                                              class: "release-form") do %>
  <%= button_tag(type: "submit", class: "button-off") do %>
  <% end %>
  <span class="light-off"></span>
<% end %>

app/views/texts/_released_form.html.erb
<span id=<%= "release-status-#{text.id}" %>>
  <% if text.released %>
    <%= render 'texts/unrelease', text: text %>
  <% else %>
    <%= render 'texts/release', text: text %>
  <% end %>
</span>

app/views/texts/_text.html.erb
<li id=<%= "text_#{text.id}" %> class="text-click">
  <% if signed_in? %>
    <span class="glyphicon glyphicon-resize-vertical sorting-handle"></span>
    <%= render 'texts/released_form', text: text %>
    <span data-no-turbolink>
      <% if current_user.id == text.user_id %>
        <%= link_to "Edit", edit_text_path(text),
                            class: "btn btn-primary btn-edit" %>
      <% elsif current_user.admin? %>
        <%= link_to "Edit", edit_text_path(text),
                            class: "btn btn-info btn-edit" %>
      <% else %>
        <%= link_to "Edit", '#', 
                            class: "btn btn-primary btn-edit",
                            disabled: true %>
      <% end %>
    </span>
  <% else %>
    <%= link_to content_tag(:span, ""), text_path(text), class: "text-link" %>
  <% end %>
  <span class="author"><%= text.author %></span>
  <span class="title"><%= text.title %></span>
</li>

app/views/texts/_text_about_edit.html.erb
<h1>Update text 'about' information</h1>

<div class="row">
  <div class="col-xs-12" id="ckeditor-about">
    <%= text_area_tag "about-editor", @about_content, class: 'ckeditor' %>
  </div>
</div>

app/views/texts/_text_info_edit.html.erb
<h1>Update text information</h1>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">
    <%= form_for(@text, remote: true) do |f| %>
      <%= render 'shared/flash_ajax', flash: flash %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
      
      <%= f.label :author %>
      <%= f.text_field :author, class: "form-control" %>
  
      <%= f.submit "Save changes",class: "btn btn-default btn-lg btn-primary", :data => { :disable_with => "Processing" } %>
    <% end %>
  </div>
</div>

app/views/texts/_text_markup.html.erb
<div class="row">
  <aside class="col-xs-4" id="definition-column">
    <section class="column-lookup">
      <%= render 'shared/lookup_box' %>
    </section>
    <section class="column-header">
      <b>Most Recently Clicked Word:</b> <span id="current-match"></span>
    </section>
    <section class="column-gloss">
      <%= render 'shared/glossary_definitions' %>
    </section>
    <section class="column-dict">
      <%= render 'shared/dictionary_definitions' %>
    </section>
    <section class="column-phrase">
      <span id="clicked-phrase"></span>
    </section>
  </aside> 
  <div class="col-xs-8" id="ckeditor-text">
    <%= text_area_tag "editor", @content, class: 'ckeditor' %>
  </div>
</div>

app/views/texts/_text_media_edit.html.erb
<h1>Manage media</h1>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <span id="media-flash"></span>
    <ul class="media-list">
      <%= render @media %>
      <li id="new-media"></li>
    </ul>
    <br>
    <%= link_to "Add New Image", new_medium_path(text: @text.id, type: "image"),
                                      class: "btn btn-primary", remote: true %>
    <%= link_to "Add New Audio", new_medium_path(text: @text.id, type: "audio"),
                                      class: "btn btn-primary", remote: true %>
    <%= link_to "Add New Video", new_medium_path(text: @text.id, type: "video"),
                                      class: "btn btn-primary", remote: true %>
    <%= link_to "Add New Link", new_medium_path(text: @text.id, type: "link"),
                                      class: "btn btn-primary", remote: true %>
  </div>
</div>
<br>
<br>

app/views/texts/_unrelease.html.erb
<%= form_tag(release_text_path(text.id), method: 'patch', remote: true,
                                              class: "release-form") do %>

  <%= button_tag(type: "submit", class: "button-on", data: { confirm:
        "Are you sure you want to remove the text from being viewable?" }) do %>
  <% end %>

  <span class="light-on"></span>
<% end %>

app/views/texts/about.html.erb
<% provide(:title, "About #{@text.title}") %>

<h1><%= "About #{@text.title}" %></h1>

<div class="row">
  <div id="about-display">
    <%= @content %>
  </div>
</div>

app/views/texts/edit.html.erb
<% provide(:title, "Edit " + @text.title) %>

<ul class="nav nav-tabs">
  <li class="active"><a href="#markup" data-toggle="tab">Markup</a></li>
  <li><a href="#info" data-toggle="tab">Display Information</a></li>
  <li><a href="#about" data-toggle="tab">About the Text</a></li>
  <li><a href="#media" data-toggle="tab">Manage Media</a></li>
  <% if current_user.admin? %>
    <li><a href="#ownership" data-toggle="tab">Ownership</a></li>
  <% end %>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="markup">
    <%= render 'text_markup' %>
  </div>
  <div class="tab-pane" id="info">
    <%= render 'text_info_edit' %>
  </div>
  <div class="tab-pane" id="about">
    <%= render 'text_about_edit' %>
  </div>
  <div class="tab-pane" id="media">
    <%= render 'text_media_edit' %>
  </div>
  <% if current_user.admin? %>
    <div class="tab-pane" id="ownership">
      Not finished: Should allow the admin user to change text's user/editor.
    </div>
  <% end %>
</div>

<%= javascript_tag do %>
  setTextId(<%= @text.id %>);

  window.onbeforeunload = function(e) {   // !!! Put elsewhere?
    return 'Please ensure that any changes to the text and the "about" text' +
           'have been saved.'
  };
<% end %>

app/views/texts/index.html.erb
<% provide(:title, 'German Texts') %>
<h1>German Texts</h1>

<div class="row">
 <div class="col-md-10 col-md-offset-1 col-sm-12">
    <% if signed_in? %>
      <ul class="texts sortable" data-no-turbolink>
        <%= render @texts %>
      </ul>
      <br>
      <button class="btn btn-primary" id="save_position">
        Save Text Order
      </button>
      <%= link_to "Add New Text", new_text_path, class: "btn btn-primary" %>
    <% else %>
      <ul class="texts">
        <%= render @texts %>
      </ul>
    <% end %>
  </div>
</div>

app/views/texts/new.html.erb
<% provide(:title, 'New Text') %>
<h1>Create New Text</h1>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3 col-xs-8 col-xs-offset-2">
    <%= form_for(@text) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.label :author %>
      <%= f.text_field :author, class: "form-control" %>

      <%= f.submit "Create a text", class: "btn btn-lg btn-primary" %>
    <% end %>
  </div>
</div>

app/views/texts/release.js.erb
$("#release-status-<%= @text.id %>").html("<%= escape_javascript(render 'texts/released_form', text: @text) %>");

app/views/texts/show.html.erb
<% provide(:title, @text.title) %>

<div class="row">
  <div id="text-display">
    <%= @content %>
  </div>
</div>

<%= javascript_tag do %>
  setGlossary(<%= raw @matches.to_json %>, <%= raw @definitions.to_json %>,
                                           <%= raw @phrases.to_json %>);
  $(".media").empty();
  $(".note").empty();
<% end %>