config/routes.rb
Annotext::Application.routes.draw do

  root  'texts#index'
  match '/help',        to: 'static_pages#help',        via: 'get'
  match '/editor_help', to: 'static_pages#editor_help', via: 'get'
  match '/about',       to: 'static_pages#about',       via: 'get'
  match '/contact',     to: 'static_pages#contact',     via: 'get'
  match '/history',     to: 'static_pages#history',     via: 'get'

  match '/signin',      to: 'sessions#new',             via: 'get'
  match '/signout',     to: 'sessions#destroy',         via: 'delete'

  match '/scripts',     to: 'scripts#index',            via: 'get'
  match '/complete',    to: 'scripts#complete',         via: 'get'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :texts do
    collection do
      get :order #'order'     # !!! Shouldn't be a get...
    end
    member do
      patch :release, :save, :delete, :save_about
      get   :about
    end
  end

  resources :media do
    member do
      get :close
    end
  end

  resources :matches,     only: [:create, :show, :edit, :update, :destroy]
  resources :phrases,     only: [:create, :show, :edit, :update, :destroy]
  resources :definitions, except: [:index] do
    member do
      post :copy_to_gloss, :copy_to_dict
      get  :close
    end
  end

  

end

app/views/layouts/_about_text_link.html.erb
<li>
  <%= link_to about_text_path(@text) do %>
    <%= content_tag(:span, "", class: "glyphicon glyphicon-info-sign") %>
    About This Text
  <% end %>
</li>

app/views/layouts/_editing_links.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= content_tag(:span, "", class: "glyphicon glyphicon-pencil") %>
    Editor Menu
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to scripts_path, :target => "_blank" do %>
        <%= content_tag(:span,"",class: "glyphicon glyphicon glyphicon-ok")%>
        Scripts
      <% end %>
    </li>
    <li class="divider"></li>
    <li>
      <%= link_to edit_user_path(current_user) do %>
        <%= content_tag(:span, "", class: "glyphicon glyphicon-user") %>
        Update Profile
      <% end %>
    </li>
    <li>
      <%= link_to current_user do %>
        <%= content_tag(:span, "",class: "glyphicon glyphicon-briefcase") %>
        My Texts
      <% end %>
    </li>
    <li class="divider"></li>
    <li>
      <%= link_to users_path do %>
        <%= content_tag(:span, "", class: "glyphicon glyphicon-list") %>
        User List
      <% end %>
    </li>
    <li class="divider"></li>
    <li>
      <%= link_to signout_path, method: "delete" do %>
        <%= content_tag(:span, "", class: "glyphicon glyphicon-log-out") %>
        Sign out
      <% end %>
    </li>
  </ul>
</li>

app/views/layouts/_footer.html.erb
<% if !editing_text? %>
  <footer class="footer">
    <small>
      <a href="http://annotext.dartmouth.edu/">Annotext</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About Annotext", about_path   %></li>
        <li><%= link_to "History",        history_path %></li>
        <li><%= link_to "Contact",        contact_path %></li>
        <% if !signed_in? %>
          <li><%= link_to "Editor",       signin_path %></li>
        <% end %>
      </ul>
    </nav>
  </footer>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-custom" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-links">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if showing_text? %>
        <div id="translation-box" class="navbar-text"></div>
      <% else %>
        <%= link_to "Annotext", root_path, id: "logo", class: "navbar-brand" %>
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-links">
      <% if params[:controller] == "media" %>
        <%= render partial: 'layouts/media_links' %>
      <% else %>
        <%= render partial: 'layouts/header_links' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_header_links.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if editing_text? %>
    <%= render partial: 'layouts/save_notification' %>
    <%= render partial: 'layouts/view_text_link' %>
  <% elsif showing_text? %>
    <%= render partial: 'layouts/search_bar' %>
    <%= render partial: 'layouts/options_dropdown' %>
    <%= render partial: 'layouts/about_text_link' %>
  <% elsif params[:controller]=="texts" && params[:action]=="about" %>
    <%= render partial: 'layouts/return_text_link' %>
  <% end %>

  <%= render partial: 'layouts/home_links' %>
  <%= render partial: 'layouts/help_links' %>

  <% if signed_in? && !showing_text? %>
    <%= render partial: 'layouts/editing_links' %>
  <% end %>
</ul>

app/views/layouts/_help_links.html.erb
<% if signed_in? && !showing_text? %>
  <li>
    <%= link_to editor_help_path, target: "_blank" do %>
      <%= content_tag(:span, "", class: "glyphicon glyphicon-question-sign") %>
      Editor Help
    <% end %>
  </li>
<% else %>
  <li>
    <%= link_to help_path do %>
      <%= content_tag(:span, "", class: "glyphicon glyphicon-question-sign") %>
      Help
    <% end %>
  </li>
<% end %>

app/views/layouts/_home_links.html.erb
<% if signed_in? %>
  <li data-no-turbolink>
    <%= link_to root_path do %>
      <%= content_tag(:span, "", class: "glyphicon glyphicon-book") %>
      Texts
    <% end %>
  </li>
<% else %>
  <li>
    <%= link_to root_path do %>
      <%= content_tag(:span, "", class: "glyphicon glyphicon-home") %>
      Home
    <% end %>
  </li>
<% end %>

app/views/layouts/_media_links.html.erb
<ul class="nav navbar-nav navbar-right">
  <li>        
    <a href="#" onclick="window.open('', '_self', ''); window.close();">              <%= content_tag(:span, "", class: "glyphicon glyphicon-remove") %>
      Close
    </a>
  </li> 
</ul>

app/views/layouts/_options_dropdown.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= content_tag(:span, "", class: "glyphicon glyphicon-cog") %>
    Options
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu" id="options-dropdown">
    <li>
      <form class="navbar-form navbar-left" onsubmit="return false;">
        <div class="checkbox">
          <label>
            <input id="media-checkbox" type="checkbox" checked="checked">
            Display Media Links
          </label>
        </div>
      </form>
    </li>
    <li>
      <form class="navbar-form navbar-left" onsubmit="return false;">
        <div class="checkbox">
          <label>
            <input id="colorize-checkbox" type="checkbox">
            Display Marked Phrases with Different Colors
          </label>
        </div>
      </form>
    </li>
  </ul>
</li>

app/views/layouts/_return_text_link.html.erb
<li>
  <%= link_to text_path(@text) do %>
    <%= content_tag(:span, "", class: "glyphicon glyphicon-bookmark") %>
    Return to Text
  <% end %>
</li>

app/views/layouts/_save_notification.html.erb
<li id="save-success" class="save-state">
  <p class="nav navbar-text">
    <span class="label label-success save-label">
      <%= content_tag(:span, "", class: "glyphicon glyphicon-floppy-saved") %>
      Save Successful!
    </span>
  </p>
</li>
<li id="save-failure" class="save-state">
  <p class="nav navbar-text">
    <span class="label label-danger save-label">
      <%= content_tag(:span, "", class: "glyphicon glyphicon-floppy-remove") %>
      Save Failed!
    </span>
  </p>
</li>

app/views/layouts/_search_bar.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= content_tag(:span, "", class: "glyphicon glyphicon-search") %>
    Search
    <b class="caret"></b>
  </a>
  <ul class="dropdown-menu" id="search-dropdown">
    <li>
      <form class="navbar-form navbar-left" role="search" onsubmit="return false;">
        <div class="input-group">
          <input type="text" id="search-input" class="form-control" placeholder="Search">
          <span class="input-group-btn">
            <button id="search-button" type="submit" class="btn btn-primary">
              Search
            </button>
          </span>
        </div>
      </form>
    </li>
  </ul>
</li>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_view_text_link.html.erb
<li>
  <%= link_to text_path(@text), target: "_blank" do %>
    <%= content_tag(:span, "", class: "glyphicon glyphicon-bookmark") %>
    View Text
  <% end %>
</li>